# Predict Career Longevity for NBA Rookies

In [1]:
#import libraries needed

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
#load the dataset
df = pd.read_csv('Train_data.csv')

In [6]:
#check for first five rows
df.head()

GP   MIN   PTS  FGM  FGA   FG%  3P Made  3PA   3P%  FTM  FTA   FT%  OREB  \
0  59.0  12.8   3.4  1.3  2.6  51.0      0.2  0.3  50.0  0.7  0.8  78.0   1.1   
1  31.0  10.7   3.4  1.2  3.3  35.3      0.5  2.1  25.8  0.5  0.9  55.2   0.3   
2  48.0   9.3   4.5  1.7  3.4  49.7      0.0  0.1   0.0  1.2  1.9  61.5   0.4   
3  80.0  27.7  11.2  3.5  9.4  37.4      1.3  4.1  32.9  2.8  3.3  85.0   0.8   
4  58.0  18.4   5.8  1.9  5.3  36.7      0.0  0.1  25.0  1.9  3.1  61.7   0.5   

   DREB  REB  AST  STL  BLK  TOV  Target  
0   2.3  3.3  0.5  0.3  0.4  0.5       1  
1   1.1  1.4  0.4  0.3  0.1  0.2       0  
2   0.8  1.2  0.8  0.5  0.4  1.0       0  
3   1.6  2.4  3.9  1.3  0.1  2.2       1  
4   0.7  1.2  1.9  1.1  0.2  1.7       0

In [7]:
df.isnull().sum()

GP         0
MIN        0
PTS        0
FGM        0
FGA        0
FG%        0
3P Made    0
3PA        0
3P%        0
FTM        0
FTA        0
FT%        0
OREB       0
DREB       0
REB        0
AST        0
STL        0
BLK        0
TOV        0
Target     0
dtype: int64

In [8]:
#check shape of the dataset
df.shape

(1101, 20)

In [9]:
features = df.drop('Target', axis=1)
target = df.Target

In [12]:
#model building

df.Target.unique()

array([1, 0], dtype=int64)

In [13]:
#Scaling the dataset
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(features,target)

array([[-4.73388705e-04, -5.14071774e-01, -7.45403710e-01, ...,
        -7.49803272e-01,  1.33276364e-01, -9.46325925e-01],
       [-1.62563489e+00, -7.75572865e-01, -7.45403710e-01, ...,
        -7.49803272e-01, -5.83313512e-01, -1.38275681e+00],
       [-6.38929695e-01, -9.49906925e-01, -4.81105452e-01, ...,
        -2.31630277e-01,  1.33276364e-01, -2.18941113e-01],
       ...,
       [ 3.47775505e-01, -4.64262043e-01, -3.60969880e-01, ...,
         2.86542717e-01, -1.05586928e-01, -5.09895038e-01],
       [-2.32639318e-01, -2.52570684e-01, -5.77213909e-01, ...,
         2.86542717e-01, -3.44450220e-01, -5.09895038e-01],
       [-2.32639318e-01,  1.04248234e+00,  1.80147041e+00, ...,
         1.84106170e+00,  1.33276364e-01,  3.62966736e-01]])

In [14]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(features, target)

RandomForestClassifier(max_depth=2, random_state=0)

In [15]:
test = pd.read_csv("Test_data.csv")
test.head()

GP   MIN  PTS  FGM  FGA   FG%  3P Made  3PA   3P%  FTM  FTA   FT%  OREB  \
0  44.0  13.0  6.6  2.5  5.6  45.3      0.4  1.3  32.7  1.1  1.7  65.3   0.8   
1  51.0   9.1  2.7  1.0  2.7  39.0      0.1  0.3  23.5  0.6  0.8  69.8   0.3   
2  51.0  15.1  5.7  2.2  5.2  41.2      0.3  0.8  32.5  1.1  1.6  69.1   0.4   
3  15.0   7.9  1.9  0.7  2.5  27.0      0.0  0.0   0.0  0.5  0.8  66.7   0.5   
4  36.0  14.4  5.8  2.3  5.4  43.1      0.0  0.1  50.0  1.1  1.4  82.0   1.1   

   DREB  REB  AST  STL  BLK  TOV  
0   0.6  1.4  1.1  0.7  0.2  1.0  
1   0.7  1.0  0.9  0.6  0.1  0.7  
2   1.3  1.7  2.1  0.7  0.0  1.4  
3   1.1  1.5  0.5  0.1  0.1  1.0  
4   1.4  2.4  0.9  0.3  0.2  0.9

In [16]:
clf.predict(test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,